Update development getting-started setup page
Bim4Everyone/bim4everyone.github.io pull request #2
Opened 2024-10-01 12:27 UTC by vlastroG

Page for developer was updated. Now it contains step-by-step guide to prepare your pc environment to creation your best plugins in Bim4Everyone. :)

2024-10-07 12:18 UTC, evantropova requested changes
Общее замечание - отслеживать длину строк

2024-10-07 12:18 UTC, evantropova commented on content/ru/docs/development/getting-started/setup/_index.md
> +В появившемся окне выберите свой аккаунт Microsoft и введите пароль. Создайте аккаунт, если у вас еще нет аккаунта Microsoft. Далее добавьте аккаунт GitHub. Если вы еще не зарегистрировались на GitHu
Поправляйте пожалуйста такие строки, чтобы они такие длинные не были

2024-10-07 12:18 UTC, evantropova commented on content/ru/docs/development/getting-started/setup/_index.md
> +Чтобы открыть настройки плагина прейдите в `Tools -> Spell Checker -> Edit Global Configuration`:
*перейдите и после слова "плагина" запятая

2024-10-07 12:18 UTC, evantropova commented on content/ru/docs/development/getting-started/setup/_index.md
> +Чтобы настроить цвет линии перейдите в `Tools -> Options -> Environment -> Fonts and Colors -> Guideline`:
после линии запятая

2024-10-07 12:18 UTC, evantropova commented on content/ru/docs/development/getting-started/setup/_index.md
> +Чтобы настроить плагин перейдите в `Tools -> Options -> VSColorOutput64`:
после слова плагин запятая

2024-10-07 12:18 UTC, evantropova commented on content/ru/docs/development/getting-started/setup/_index.md
> +Для разработки плагинов на python необходимо установить последнюю версию `Python2.7` (не путать с [IronPython2.7](https://ironpython.net/)). Для этого перейдите по [ссылке](https://www.python.org/dow
после python запятая

2024-10-07 12:18 UTC, evantropova commented on content/ru/docs/development/getting-started/setup/_index.md
> +В открывшемся окне выберите раздел Virtual Environment. В качестве Base interpreter укажите путь к python.exe (python2.7 который вы устанавливали выше). Т.к. stub файлы различные для каждой версии Re
после слова соответственно запятая. Строчка слишком длинная. Не указываете, а указывайте

2024-10-07 12:18 UTC, evantropova commented on content/ru/docs/development/getting-started/setup/_index.md
> +Затем необходимо настроить пути для каждого интерпретатора. Чтобы открыть окно настроек нажмите ПКМ на интерпретатор и выберите `Show Interpreter Paths`:
после окно настроек запятая

2024-10-07 12:18 UTC, evantropova commented on content/ru/docs/development/getting-started/setup/_index.md
> +И замените существующий весь текст на следующий:
не существующий весь, а весь существующий

2024-10-08 06:21 UTC, dosymep requested changes

2024-10-08 06:21 UTC, dosymep commented on content/ru/docs/development/getting-started/setup/_index.md
> +## Подключение [DevExpress](https://www.devexpress.com/)
я думаю установку девэкспресса можно удалить

2024-10-08 06:21 UTC, dosymep commented on content/ru/docs/development/getting-started/setup/_index.md
> +Ниже описаны необходимые и рекомендуемые инструменты для разработки платформы. Убедитесь, что перед началом работы на вашем ПК установлен Autodesk Revit, а также установлена сама платформа Bim4Everyo
я думаю стоит попробовать разделить эту статью на несколько

- установка программ (гит, питон, нотпад)
- установка студии (сюда может стоит добавить установку инструментов)
- установка пайшарма
- установка плагинов в ревит

2024-10-09 13:51 UTC, vlastroG commented on content/ru/docs/development/getting-started/setup/_index.md
> +Ниже описаны необходимые и рекомендуемые инструменты для разработки платформы. Убедитесь, что перед началом работы на вашем ПК установлен Autodesk Revit, а также установлена сама платформа Bim4Everyo
Разделил на разные статьи

2024-10-09 13:51 UTC, vlastroG commented on content/ru/docs/development/getting-started/setup/_index.md
> +## Подключение [DevExpress](https://www.devexpress.com/)
Убрал

2024-10-09 14:23 UTC, vlastroG commented on content/ru/docs/development/getting-started/setup/_index.md
> +В появившемся окне выберите свой аккаунт Microsoft и введите пароль. Создайте аккаунт, если у вас еще нет аккаунта Microsoft. Далее добавьте аккаунт GitHub. Если вы еще не зарегистрировались на GitHu
скорректировал

2024-10-09 14:25 UTC, vlastroG commented on content/ru/docs/development/getting-started/setup/_index.md
> +Чтобы открыть настройки плагина прейдите в `Tools -> Spell Checker -> Edit Global Configuration`:
добавил

2024-10-09 14:25 UTC, vlastroG commented on content/ru/docs/development/getting-started/setup/_index.md
> +Чтобы настроить цвет линии перейдите в `Tools -> Options -> Environment -> Fonts and Colors -> Guideline`:
добавил

2024-10-09 14:27 UTC, vlastroG commented on content/ru/docs/development/getting-started/setup/_index.md
> +Чтобы настроить плагин перейдите в `Tools -> Options -> VSColorOutput64`:
добавил

2024-10-09 14:27 UTC, vlastroG commented on content/ru/docs/development/getting-started/setup/_index.md
> +Для разработки плагинов на python необходимо установить последнюю версию `Python2.7` (не путать с [IronPython2.7](https://ironpython.net/)). Для этого перейдите по [ссылке](https://www.python.org/dow
добавил

2024-10-09 14:28 UTC, vlastroG commented on content/ru/docs/development/getting-started/setup/_index.md
> +В открывшемся окне выберите раздел Virtual Environment. В качестве Base interpreter укажите путь к python.exe (python2.7 который вы устанавливали выше). Т.к. stub файлы различные для каждой версии Re
скорректировал

2024-10-09 14:29 UTC, vlastroG commented on content/ru/docs/development/getting-started/setup/_index.md
> +Затем необходимо настроить пути для каждого интерпретатора. Чтобы открыть окно настроек нажмите ПКМ на интерпретатор и выберите `Show Interpreter Paths`:
добавил

2024-10-09 14:29 UTC, vlastroG commented on content/ru/docs/development/getting-started/setup/_index.md
> +И замените существующий весь текст на следующий:
скорректировал

2024-10-10 08:33 UTC, dosymep requested changes
Добавь категории и теги на страницах

2024-10-10 08:33 UTC, dosymep commented on content/ru/docs/development/getting-started/setup/_index.md
> +## Оглавление
я думаю оглавление тут не нужно, так как сразу после него идет встроенное оглавление

2024-10-10 08:33 UTC, dosymep commented on content/ru/docs/development/getting-started/setup/_index.md
> +В данном разделе описаны необходимые и рекомендуемые инструменты для разработки платформы. Убедитесь, что перед началом работы на вашем ПК установлен Autodesk Revit, а также установлена сама платформ
слишком длинная строка

2024-10-10 08:33 UTC, dosymep commented on content/ru/docs/development/getting-started/setup/core-apps/_index.md
> +## [Git](https://git-scm.com/)
рекомендую эту ссылку вынести в описание инструмента

2024-10-10 08:33 UTC, dosymep commented on content/ru/docs/development/getting-started/setup/core-apps/_index.md
> +В ```user.email``` напишите свой email, который привязан к [GitHub](https://github.com/):
добавь `свой публичный email`

2024-10-10 08:33 UTC, dosymep commented on content/ru/docs/development/getting-started/setup/core-apps/_index.md
> +## [Python](https://www.python.org/)
ссылку добавь в описание

2024-10-10 08:33 UTC, dosymep commented on content/ru/docs/development/getting-started/setup/pycharm/_index.md
> +Скачайте архив с RevitAPIStubs по [ссылке](https://github.com/BIMOpenGroup/RevitAPIStubs/releases/tag/v1.0.0). В этом архиве находится python код,
укажи `latest` версию ссылки

2024-10-10 08:33 UTC, dosymep commented on content/ru/docs/development/getting-started/setup/pycharm/_index.md
> +Перед тем, как добавлять интерпретаторы, убедитесь, что на вашем ПК установлена сама платформа Bim4Everyone.
можешь тут сослаться на статью по установке `getting-started/install`

2024-10-10 08:33 UTC, dosymep commented on content/ru/docs/development/getting-started/setup/pycharm/_index.md
> +В открывшемся окне выберите раздел Virtual Environment. В качестве Base interpreter укажите путь к python.exe
python.exe - выдели этот текст

2024-10-10 08:33 UTC, dosymep commented on content/ru/docs/development/getting-started/setup/core-apps/_index.md
> +title: Установка Git, Python, Notepad++
думаю стоит написать абстрактно, чтобы при добавлении нового ПО не было проблем `Необходимое ПО`

2024-10-10 14:29 UTC, vlastroG commented on content/ru/docs/development/getting-started/setup/_index.md
> +## Оглавление
убрал

2024-10-10 14:30 UTC, vlastroG commented on content/ru/docs/development/getting-started/setup/_index.md
> +В данном разделе описаны необходимые и рекомендуемые инструменты для разработки платформы. Убедитесь, что перед началом работы на вашем ПК установлен Autodesk Revit, а также установлена сама платформ
скорректировал

2024-10-10 14:30 UTC, vlastroG commented on content/ru/docs/development/getting-started/setup/pycharm/_index.md
> +Перед тем, как добавлять интерпретаторы, убедитесь, что на вашем ПК установлена сама платформа Bim4Everyone.
добавил

2024-10-10 14:31 UTC, vlastroG commented on content/ru/docs/development/getting-started/setup/core-apps/_index.md
> +title: Установка Git, Python, Notepad++
скорректировал

2024-10-10 14:34 UTC, vlastroG commented on content/ru/docs/development/getting-started/setup/pycharm/_index.md
> +В открывшемся окне выберите раздел Virtual Environment. В качестве Base interpreter укажите путь к python.exe
готово

2024-10-10 14:34 UTC, vlastroG commented on content/ru/docs/development/getting-started/setup/core-apps/_index.md
> +В ```user.email``` напишите свой email, который привязан к [GitHub](https://github.com/):
добавил

2024-10-10 14:37 UTC, vlastroG commented on content/ru/docs/development/getting-started/setup/pycharm/_index.md
> +Скачайте архив с RevitAPIStubs по [ссылке](https://github.com/BIMOpenGroup/RevitAPIStubs/releases/tag/v1.0.0). В этом архиве находится python код,
добавил

2024-10-10 14:54 UTC, vlastroG commented on content/ru/docs/development/getting-started/setup/core-apps/_index.md
> +## [Git](https://git-scm.com/)
скорректировал

2024-10-10 14:54 UTC, vlastroG commented on content/ru/docs/development/getting-started/setup/core-apps/_index.md
> +## [Python](https://www.python.org/)
скорректировал

2024-10-11 15:08 UTC, evantropova requested changes
ничего критичного, там можно быстро исправить

2024-10-11 15:08 UTC, evantropova commented on content/ru/docs/development/getting-started/setup/core-apps/_index.md
> +Если вы продвинутый пользователь, вы уже сами знаете, что вам нужно.
**то** вы уже сами...

2024-10-11 15:08 UTC, evantropova commented on content/ru/docs/development/getting-started/setup/core-apps/_index.md
> +Для разработки плагинов на python, необходимо установить последнюю версию `Python2.7` (не путать с [IronPython2.7](https://ironpython.net/)).
после слова python запятая не нужна

2024-10-11 15:08 UTC, evantropova commented on content/ru/docs/development/getting-started/setup/core-apps/_index.md
> +[Notepad++](https://notepad-plus-plus.org/) - это очень удобный бесплатный текстовый редактор для любого формата файлов.
я бы не стала писать здесь "очень". Редактор или удобный или нет

2024-10-11 15:08 UTC, evantropova commented on content/ru/docs/development/getting-started/setup/pycharm/_index.md
> +то под каждую версию Revit необходимо создавать свой интерпретатор.
Я бы немного упростила предложение. Например, "Т.к. stub файлы отличаются для каждой версии Revit, то нужно создать интерпретаторы под все версии revit, которые у вас установлены, и положить их в отдельные папки. Папки укажите в Location".

2024-10-11 15:08 UTC, evantropova commented on content/ru/docs/development/getting-started/setup/revit-plugins/_index.md
> +На данной странице приведены одни из самых полезных из них.
приведены самые полезные из них

2024-10-11 15:08 UTC, evantropova commented on content/ru/docs/development/getting-started/setup/visual-studio/_index.md
> +Когда появится окно для установки Visual Studio Community 2022 выберите следующие опции:
после 2022 запятая

2024-10-11 15:08 UTC, evantropova commented on content/ru/docs/development/getting-started/setup/visual-studio/_index.md
> +Чтобы добавить слово в словарь исключений необходимо нажать `Alt+Enter`:
исключений,

2024-10-14 07:26 UTC, vlastroG commented on content/ru/docs/development/getting-started/setup/visual-studio/_index.md
> +Чтобы добавить слово в словарь исключений необходимо нажать `Alt+Enter`:
скорректировал

2024-10-14 07:26 UTC, vlastroG commented on content/ru/docs/development/getting-started/setup/visual-studio/_index.md
> +Когда появится окно для установки Visual Studio Community 2022 выберите следующие опции:
скорректировал

2024-10-14 07:26 UTC, vlastroG commented on content/ru/docs/development/getting-started/setup/revit-plugins/_index.md
> +На данной странице приведены одни из самых полезных из них.
скорректировал

2024-10-14 07:26 UTC, vlastroG commented on content/ru/docs/development/getting-started/setup/pycharm/_index.md
> +то под каждую версию Revit необходимо создавать свой интерпретатор.
скорректировал

2024-10-14 07:26 UTC, vlastroG commented on content/ru/docs/development/getting-started/setup/core-apps/_index.md
> +[Notepad++](https://notepad-plus-plus.org/) - это очень удобный бесплатный текстовый редактор для любого формата файлов.
убрал

2024-10-14 07:26 UTC, vlastroG commented on content/ru/docs/development/getting-started/setup/core-apps/_index.md
> +Для разработки плагинов на python, необходимо установить последнюю версию `Python2.7` (не путать с [IronPython2.7](https://ironpython.net/)).
убрал

2024-10-14 07:26 UTC, vlastroG commented on content/ru/docs/development/getting-started/setup/core-apps/_index.md
> +Если вы продвинутый пользователь, вы уже сами знаете, что вам нужно.
добавил

2024-10-15 06:14 UTC, dosymep approved these changes

2024-10-15 06:19 UTC, merged