Add user install article
Bim4Everyone/bim4everyone.github.io pull request #6
Opened 2024-10-16 07:52 UTC by sssenya

Added three articles for platform users:

- install
- setup
- update

2024-10-16 08:48 UTC, dosymep requested changes
- удали в статье "Начало работы" текст "Здесь будет круто..."
- настрой порядок статей "Установка, Настройка, Обновление"
- добавь всем статьям краткое описание
- настрой теги и категории, категорий должно быть не много, а тегов побольше, по сути каждый термин, который встречается в статье
- добавь статью удаление платформы

я забыл пометить еще, покажи в установке, как выбрать нужную вкладку, были проблемы с тем что там много вариантов выбора и неясно какой надо выбрать - я про место в установщике, где выбор вкладок

2024-10-16 08:48 UTC, dosymep commented on content/ru/docs/user/getting-started/install/_index.md
> +7. После этого на ленте Revit должны появиться выбранные при установке вкладки.
сбилась нумерация

2024-10-16 08:48 UTC, dosymep commented on content/ru/docs/user/getting-started/install/_index.md
> +<img src="install-2.png" width="420" />
там появляется другая картинка после установки, надстройка pyRevit у нас подписана https://pyrevitlabs.notion.site/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2Ffe8ed854-a0cc-48a7-b8b8-9ec060e84d26%2F2018-06-28_16_56_45-Window.png?table=block&id=cb879840-10dd-40a1-959c-d16c7619b2b0&spaceId=04c247a1-0126-4db4-b5b2-e1ccf6fbbde5&width=1060&userId=&cache=v2

2024-10-16 08:48 UTC, dosymep commented on content/ru/docs/user/getting-started/setup/_index.md
> +В данном окне можно изменить глобальные настройки платформы, настройки вкладок, настройки телеметрии  т.д.
в строке есть лишний пробел

2024-10-16 08:48 UTC, dosymep commented on content/ru/docs/user/getting-started/setup/_index.md
> +Здесь доступны непосредственно вкладки Bim4Everyone, а также вкладки pyRevit.
добавь инструкцию как включать\выключать и настраивать уведомления, они в панели `Основные` в самом низу

2024-10-16 08:48 UTC, dosymep commented on content/ru/docs/user/getting-started/update/_index.md
> +Платформа состоит из двух основных частей - скриптов и непосредственно самой платформы, которая используется всеми скриптами.
вообще трех, еще мы в установщике, иногда сам pyRevit обновляем, думаю про него имеет смысл тоже написать

2024-10-16 08:48 UTC, dosymep commented on content/ru/docs/user/getting-started/update/_index.md
> +Для установки обновлений необходимо запустить файл-установщик (аналогично [установке платформы](../install)) и следовать его инструкциям.
думаю тут в конце можно добавить про проблемы работы, о которых мы знаем, но пока поправить не можем


- если редко перезапускают ревит, то может поломаться обновление (тогда надо восстановить или переустановить платформу)
- если после первой установки в ревит не появились вкладки, то можно платформу попробовать восстановить или переустановить (типа часто со второго раза все хорошо)

2024-10-16 08:58 UTC, evantropova submitted a review, later dismissed

2024-10-18 09:55 UTC, sssenya commented on content/ru/docs/user/getting-started/update/_index.md
> +Платформа состоит из двух основных частей - скриптов и непосредственно самой платформы, которая используется всеми скриптами.
я просто упомянул PyRevit, чтобы не усложнять для пользователя структуру платформы)

2024-10-18 09:55 UTC, sssenya commented on content/ru/docs/user/getting-started/update/_index.md
> +Для установки обновлений необходимо запустить файл-установщик (аналогично [установке платформы](../install)) и следовать его инструкциям.
я решил сделать отдельную статью про ошибки, чтобы они в одном месте упоминались
думаю так проще будет найти

2024-10-21 07:27 UTC, dosymep requested changes
- проверь расположение всех картинок
- для всех заголовков лучше использовать `##`, тогда у статьи появится автосодержание

2024-10-21 07:27 UTC, dosymep commented on content/ru/docs/user/getting-started/install/_index.md
> +<img src="install-1.png" width="420"/>
Верстка картинок поехала, надо оставлять пустую строку

2024-10-21 07:27 UTC, dosymep commented on content/ru/docs/user/getting-started/update/_index.md
> +description:
Добавь описание к статье

2024-10-21 07:27 UTC, dosymep commented on content/ru/docs/user/getting-started/_index.md
> +tags: [docs, install, setup, delete, update, scripts, tabs, github, pyRevit, Revit, fix, errors, problems]
мы кстати до этого не писали все теги на начальной статье, может быть это имеет смысл? Обычно в начальной статье не так много всего

2024-10-21 09:45 UTC, sssenya commented on content/ru/docs/user/getting-started/_index.md
> +tags: [docs, install, setup, delete, update, scripts, tabs, github, pyRevit, Revit, fix, errors, problems]
имеет смысл писать или не писать? С одной стороны в статье ничего нет почти, но с тегами из вложенных статей она вылезет тоже в поиске по тегу, но вопрос нужно ли это...

в общем удалил теги

2024-10-21 14:27 UTC, evantropova requested changes
Я немного изменила формулировки, гляньте пожалуйста

2024-10-21 14:27 UTC, evantropova commented on content/ru/docs/user/getting-started/delete/_index.md
> +Удалить платформу можно с помощью установщика той версии платформа, которая у вас установлена на данный момент.
платформЫ

2024-10-21 14:27 UTC, evantropova commented on content/ru/docs/user/getting-started/problems/_index.md
> +В данной статье описаны проблемы и способы их решения. В дальнейшем эти проблемы будут исправлены.
я бы написала "в этой статье описаны способы их решения". А то много раз повторяется слово проблемы

2024-10-21 14:27 UTC, evantropova commented on content/ru/docs/user/getting-started/problems/_index.md
> +Иногда могут возникнуть неожиданные проблемы при запуске скриптов. Это может быть связанно с отсутствием обновлений
связано (с одной н)

2024-10-21 14:27 UTC, evantropova commented on content/ru/docs/user/getting-started/problems/_index.md
> +Если после завершения установки вкладки платформы не появились в Revit, то рекомендуется пройти процедуру
почему бы не заменить везде слово "рекомендуется" на "рекомендуем"? Я не настаиваю, но на мой взгляд это звучит легче

2024-10-21 14:27 UTC, evantropova commented on content/ru/docs/user/getting-started/setup/_index.md
> +В данном разделе можно настроить основные свойства платформы, например, внешний вид и уведомления.
Я бы разделила на два предложения. Перед например поставила бы точку

2024-10-21 14:27 UTC, evantropova commented on content/ru/docs/user/getting-started/setup/_index.md
> +Здесь доступны непосредственно вкладки Bim4Everyone, а также вкладки pyRevit.
Здесь доступны вкладки BIM4Everyone и pyRevit

2024-10-21 14:27 UTC, evantropova commented on content/ru/docs/user/getting-started/update/_index.md
> +Платформа состоит из двух основных частей - скриптов и непосредственно самой платформы (созданной на основе pyRevit),
я бы написала "Платформа состоит из двух основных частей - скриптов и самой платформы, которая используется всеми скриптами"

2024-10-21 14:27 UTC, evantropova commented on content/ru/docs/user/getting-started/update/_index.md
> +Версии платформы указываются в формате "v00.00.00". Версия прописывается в имени файла установщика,
вместо запятой я бы использовала "и"

2024-10-21 14:27 UTC, evantropova commented on content/ru/docs/user/getting-started/update/_index.md
> +видна в процессе установки, а текущую версию можно узнать в окне "Приложения и возможности" в параметрах Windows
Про текущую версию лучше отдельным предложением и без "а"

2024-10-22 14:58 UTC, evantropova approved these changes
красота)

2024-10-24 08:00 UTC, dosymep approved these changes

2024-10-24 08:01 UTC, merged