Added Platform Parameters page
Bim4Everyone/bim4everyone.github.io pull request #8
Opened 2024-12-10 11:56 UTC by DivinN

An article on the topic of Platform Parameters has been added. Please read it and provide your comments for edits.

Suggestion: to allocate this material to a separate article or block of articles, since this topic is only one of those related to the topic of Concept.

2024-12-12 08:04 UTC, dosymep requested changes
текст надо бы переформулировать, у тебя слишком часто встречаются слова платформа, параметры и т.п., так же надо бы перенести суть того зачем оно так сделано.

Answer: Sorry, my dear friend, I don't understand Russian, please write in English

2024-12-12 08:04 UTC, dosymep commented on content/ru/docs/development/concepts.md
> +## Введение
вынеси в отдельную статью "Параметры платформы", заполнить нужно теги и категории

2024-12-12 08:04 UTC, dosymep commented on content/ru/docs/development/concepts.md
> +В платформе реализован подход с хранением параметров, которые используются в плагинах постоянно.
Хранение параметров странно звучит, скорее настройка, или создание реестра параметров. "Постоянно" - удали

2024-12-12 08:04 UTC, dosymep commented on content/ru/docs/development/concepts.md
> +- предоставлять базовый функционал по работе с параметрами разработчикам плагинов с уже встроенными проверками
тут статья уже для разработчиков, и все эти фичи для разработчиков плагинов, думаю повторно об этом напоминать не надо :)

2024-12-12 08:04 UTC, dosymep commented on content/ru/docs/development/concepts.md
> +- быстро копировать параметры в проект при запуске плагинов;
Быстроты тут нет, скорее удобное апи для переноса используемых платформой параметров в проект

2024-12-12 08:04 UTC, dosymep commented on content/ru/docs/development/concepts.md
> +- файл Revit, который используется как шаблон-хранилище, из которого производится копирование параметров
слишком часто встречается который\которого

2024-12-12 08:04 UTC, dosymep commented on content/ru/docs/development/concepts.md
> +- файл Revit, который используется как шаблон-хранилище, из которого производится копирование параметров
проще написать, используется файл ревит, как шаблон хранилище, откуда переносятся параметры в проект

2024-12-12 08:04 UTC, dosymep commented on content/ru/docs/development/concepts.md
> +- RevitParam:
надо отсортировать, "общий, проекта, системный", либо "системный, общий, проекта"

2024-12-12 08:04 UTC, dosymep commented on content/ru/docs/development/concepts.md
> +- RevitParam:
вообще слишком многословно выходит у тебя, надо бы как-то тут по другому написать

2024-12-12 08:04 UTC, dosymep commented on content/ru/docs/development/concepts.md
> +Файл-шаблон Revit используется платформой для хранения параметров, которые в дальнейшем через методы платформы
Файл шаблон, используется для хранения параметров, так как в Revit сложно или невозможно создать параметры в проекте, то из данного файла параметры переносятся в проект, путем копирования элементов параметров.


Короче я думаю важно указать, что параметры копируются из этого файла, потому что типа сложно. Ну короче написать зачем он нужен, а не просто его функцию.

2024-12-12 08:04 UTC, dosymep commented on content/ru/docs/development/concepts.md
> +*%appdata%\pyRevit\Extensions\BIM4Everyone.lib\dosymep_libs\libs\<Revit version>\templates\project_parameters.rvt*
добавь еще что пока что, он находится рядом с библиотекой платформы dosymep.Bim4Everyone.dll

2024-12-12 08:04 UTC, dosymep commented on content/ru/docs/development/concepts.md
> +Также файл-шаблон можно открыть при помощи кнопки "Открыть шаблон параметров" на вкладке Admin платформы в Revit.
убери также

2024-12-12 08:04 UTC, dosymep commented on content/ru/docs/development/concepts.md
> +Через кнопку Параметры проекта на вкладке Управление можно увидеть перечень всех параметров, которые добавлены
тут скрин нужен, переформулируй предложения не используя слово через

2024-12-12 08:04 UTC, dosymep commented on content/ru/docs/development/concepts.md
> +**Save** - метод класса конфигурации, который производит сохранение конфигурации в файл JSON-формата по указанному пути.
удали все что тут написано, про сохранение и загрузку

2024-12-12 08:04 UTC, dosymep commented on content/ru/docs/development/concepts.md
> +Есть возможность настроить платформу таким образом, чтобы определенная загружаемая конфигурация загружалась всегда.
удали все, оставь только то что, загрузка параметров происходит в файле startup.py

2024-12-12 08:04 UTC, dosymep commented on content/ru/docs/development/concepts.md
> +В платформе присутствует классы DocumentExtensions, ElementExtensions и т.п. благодаря которым есть возможность
лучше про конкретные классы не писать, а просто сказать, что есть специальные классы расширения, в которых есть методы по работе с параметрами и их указать, и написать абстрактно, а не тупо все

2024-12-12 08:04 UTC, dosymep commented on content/ru/docs/development/concepts.md
> +## Структура классов платформы
удали все до конца с этой строчки, ее всю целиком можно заменить ссылкой на документацию самой библиотеки

2024-12-12 08:04 UTC, dosymep commented on content/ru/docs/development/concepts.md
> +Конфигурация параметров - это набор параметров платформы, с которыми можно работать при помощи функционала платформы.
перефразируй текст

2024-12-12 09:00 UTC, DivinN commented on content/ru/docs/development/concepts.md
> +- быстро копировать параметры в проект при запуске плагинов;
То есть вы хотите сказать, что этот подход не ускоряет процесс переноса параметров?

2024-12-12 09:06 UTC, DivinN commented on content/ru/docs/development/concepts.md
> +- файл Revit, который используется как шаблон-хранилище, из которого производится копирование параметров
Да, благодарю, ваш вариант гораздо лучше

2024-12-12 09:10 UTC, DivinN commented on content/ru/docs/development/concepts.md
> +- RevitParam:
Не спорю, хочется услышать ваши предложения какую информацию стоит убрать с учетом того, что мы убираем целый блок по структуре

2024-12-12 09:21 UTC, DivinN commented on content/ru/docs/development/concepts.md
> +*%appdata%\pyRevit\Extensions\BIM4Everyone.lib\dosymep_libs\libs\<Revit version>\templates\project_parameters.rvt*
Никто не знает, где находится библиотека платформы, т.к. об этом нигде не говорится, поэтому не считаю целесообразным говорить об этом

2024-12-16 09:20 UTC, vlastroG requested changes
- Сделай выделение всего кода (примеры названий методов и классов) с использованием `кода`
- Примеры вызовов методов помести в большие блоки кода:
```
Console.WriteLine("Sample");
```

- Пути к файлам напиши ***жирным курсивом***
- Отдели заголовки (##) сверху и снизу 1 пустой строкой

2024-12-16 09:20 UTC, vlastroG commented on content/ru/docs/development/overview.md
> +Доступны в следующей статье: [Концепции](concepts/_index.md)
в development/concepts/_index.md надо убрать дефолтный текст "будет круто" и написать более развернуто, почему уже сейчас круто :)

2024-12-16 09:20 UTC, vlastroG commented on content/ru/docs/development/concepts/platform-parameters.md
> +<img src="platform-parameters-1.png" width="300"/>
изображение на мой взгляд маловато для отображения в браузере

2024-12-16 09:20 UTC, vlastroG commented on content/ru/docs/development/concepts/platform-parameters.md
> +  - SystemParamConfig - класс конфигурации системных параметров Revit (в нем хранятся системные параметры конфигурации по умолчанию).
названия классов лучше как-то визуально выделить, можно сделать `кодом` , жирным **`кодом`** или какую-то другую комбинацию с символами \` \`

2024-12-16 09:20 UTC, vlastroG commented on content/ru/docs/development/concepts/platform-parameters.md
> +2. далее если параметр не был найден в целевом проекте, то производится копирование нужного параметра.
Напиши пункты списка с большой буквы как и везде в статье

2024-12-17 09:00 UTC, vlastroG requested changes

2024-12-17 09:00 UTC, vlastroG commented on content/ru/docs/development/concepts/_index.md
> +пользователям максимальное количество инструментов в кратчайшие сроки.
Изучив данный раздел, (**запятая**) вы сможете применять весь функционал, (**запятая**) заложенный в платформу, (**запятая**) при разработке своих решений автоматизации, предлагая пользователям максимальное количество инструментов в кратчайшие сроки.

2024-12-17 09:00 UTC, vlastroG commented on content/ru/docs/development/concepts/platform-parameters.md
> +  - **`SystemParamConfig`** - класс конфигурации системных параметров Revit (в нем хранятся системные параметры конфигурации по умолчанию).
Скорректируй названия классов здесь и далее: RevitParam_s_Config

2024-12-17 09:00 UTC, vlastroG commented on content/ru/docs/development/concepts/platform-parameters.md
> +### Получение значения параметра
для таких заголовков тоже сделай отступ сверху и снизу в 1 пустую строку

2024-12-17 09:00 UTC, vlastroG commented on content/ru/docs/development/concepts/platform-parameters.md
> +(сниматься галочки категорий, не будут);
сниматься галочки категорий (*запятая не нужна*) не будут

2024-12-17 09:00 UTC, vlastroG commented on content/ru/docs/development/concepts/platform-parameters.md
> +**`IsExistsParam`** - метод, который проверяет есть ли параметр у элемента. Возвращает `true`, если есть. При этом проверка
который проверяет, (*запятая*) есть ли

2024-12-17 11:08 UTC, vlastroG approved these changes

2024-12-17 12:04 UTC, sssenya approved these changes

2024-12-17 12:08 UTC, merged